"""Initial migration.

Revision ID: 21d0d51df667
Revises: 
Create Date: 2026-09-17 21:16:20.596619

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '21d0d51df667'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('date_birth', sa.Date(), nullable=False),
                    sa.Column('wanted', sa.Boolean(), nullable=False),
                    sa.Column('reason', sa.String(length=200), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('embedding',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('person_id', sa.Integer(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=512), nullable=False),
                    sa.Column('model', sa.String(length=20), nullable=False),
                    sa.Column('dimension', sa.Integer(), nullable=False),
                    sa.Column('angle', sa.String(length=20), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['person_id'], ['person.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('embedding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embedding_person_id'), [
                              'person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embedding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embedding_person_id'))

    op.drop_table('embedding')
    op.drop_table('person')
    # ### end Alembic commands ###
