"""Adicionado tabela de sincronicação de mudanças

Revision ID: d34172917079
Revises: 21d0d51df667
Create Date: 2026-09-26 23:54:06.427111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34172917079'
down_revision = '21d0d51df667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_change',
                    sa.Column('version', sa.Integer(), nullable=False),
                    sa.Column('table_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('register_id', sa.Integer(), nullable=False),
                    sa.Column('operation', sa.String(
                        length=10), nullable=False),
                    sa.Column('people_max_id', sa.Integer(), nullable=True),
                    sa.Column('embedded_max_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('version')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_change')
    # ### end Alembic commands ###
